os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - lib32stdc++6
      - lib32z1
      - lib32z1-dev
      - gcc-multilib
      - python-dev
      - python3
      - openssl
      - libssl-dev
language: python
python: "2.7"
script:
  - find /usr -iname openssl
