language: go

go:
  - 1.9

before_install:
  - go get -v github.com/golang/lint/golint

script:
  - BAD_FILES=$(gofmt -l .) && [[ -z "${BAD_FILES}" ]] || echo >&2 "Badly formatted files:" && echo "${BAD_FILES}" && exit 1
  - golint ./...
  - go build
  - go test ./...
  - go tool vet .
